(defun clear-shell ()
  (interactive)
  (if (eql major-mode 'cider-repl-mode)
      (cider-repl-clear-buffer)
    (let ((old-max comint-buffer-maximum-size))
      (setq comint-buffer-maximum-size 0)
      (comint-truncate-buffer)
      (setq comint-buffer-maximum-size old-max))))

(global-set-key (kbd "C-x c") 'clear-shell)
(global-set-key (kbd "C-x j") 'ace-jump-word-mode)
(global-set-key (kbd "C-c a") 'ace-jump-mode)
